### ISSUE TITLE
cblas dependency on Bonna HPC

### ISSUE THREAD

**Issue by dilpath** [ICB-DCM/AMICI#1048]
I encountered this issue a while ago and Bonna support haven't responded yet, so maybe this can be fixed in AMICI, since I understand it's important for a COVID-19 study (@elbaraim @JanHasenauer ). 

# Installation attempt 1
1. Load required modules: `module load Anaconda3 SWIG HDF5 OpenBLAS CMake Boost`
```
$ module list

Currently Loaded Modules:
  1) Anaconda3/2019.03             9) numactl/2.0.12-GCCcore-8.3.0     17) HDF5/1.10.5-gompi-2019b
  2) GCCcore/8.3.0                10) XZ/5.2.4-GCCcore-8.3.0           18) OpenBLAS/0.3.7-GCC-8.3.0
  3) zlib/1.2.11-GCCcore-8.3.0    11) libxml2/2.9.9-GCCcore-8.3.0      19) ncurses/6.1-GCCcore-8.3.0
  4) bzip2/1.0.8-GCCcore-8.3.0    12) libpciaccess/0.14-GCCcore-8.3.0  20) cURL/7.66.0-GCCcore-8.3.0
  5) PCRE/8.43-GCCcore-8.3.0      13) hwloc/1.11.12-GCCcore-8.3.0      21) CMake/3.15.3-GCCcore-8.3.0
  6) SWIG/4.0.1-GCCcore-8.3.0     14) OpenMPI/3.1.4-GCC-8.3.0          22) Boost/1.71.0-gompi-2019b
  7) binutils/2.32-GCCcore-8.3.0  15) gompi/2019b
  8) GCC/8.3.0                    16) Szip/2.1.1-GCCcore-8.3.0
```
2. Clone AMICI: `git clone https://github.com/ICB-DCM/AMICI`
3. `cd AMICI/python/sdist`
4. Checkout the develop branch: `git checkout develop`
5. Install to your local user:
```
$ pip install --user -e .
# other output before the error message...
g++ -pthread -shared -B /opt/software/easybuild/software/Anaconda3/2019.03/compiler_compat -L/opt/software/easybuild/software/Anaconda3/2019.03/lib -Wl,-rpath=/opt/software/easybuild/software/Anaconda3/2019.03/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/amici/amici_wrap.o -L/opt/software/easybuild/software/HDF5/1.10.5-gompi-2019b/lib -Lamici/libs -Lbuild/temp.linux-x86_64-3.7 -lamici -lsundials -lsuitesparse -o build/lib.linux-x86_64-3.7/amici/_amici.cpython-37m-x86_64-linux-gnu.so -lcblas -lhdf5_hl_cpp -lhdf5_hl -lhdf5_cpp -lhdf5
/opt/software/easybuild/software/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: error: cannot find -lcblas
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
```
# Installation attempt 2
Identical to Installation attempt 1 until step 5:
5. Make `cblas` available to the linker: `export BLAS_CFLAGS="/opt/software/easybuild/software/OpenBLAS/0.3.7-GCC-8.3.0/include"`
6. Install to your local user: `pip install --user -e .`. Now installs without error.

# Test installation
- with `model_steadystates_scaled.xml`
- Script
```
$ cat run.py
import libsbml
import importlib
import amici
import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import logging

sbml_file = 'model_steadystate_scaled.xml'
model_name = 'model_steadystate_scaled'
model_output_dir = model_name

sbml_importer = amici.SbmlImporter(sbml_file)
constantParameters = ['k0']
observables = {
    'observable_x1': {'name': '', 'formula': 'x1'},
    'observable_x2': {'name': '', 'formula': 'x2'},
    'observable_x3': {'name': '', 'formula': 'x3'},
    'observable_x1_scaled': {'name': '', 'formula': 'scaling_x1 * x1'},
    'observable_x2_offsetted': {'name': '', 'formula': 'offset_x2 + x2'},
    'observable_x1withsigma': {'name': '', 'formula': 'x1'}
}
sigmas = {'observable_x1withsigma': 'observable_x1withsigma_sigma'}
sbml_importer.sbml2amici(model_name,
                         model_output_dir,
                         verbose=logging.INFO,
                         observables=observables,
                         constantParameters=constantParameters,
                         sigmas=sigmas)
```
- Error:
```
$ python run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    import amici
  File "/home/dpathirana/software/ICB-DCM/AMICI/python/sdist/amici/__init__.py", line 121, in <module>
    raise e
  File "/home/dpathirana/software/ICB-DCM/AMICI/python/sdist/amici/__init__.py", line 89, in <module>
    from . import amici
  File "/home/dpathirana/software/ICB-DCM/AMICI/python/sdist/amici/amici.py", line 30, in <module>
    from . import _amici
ImportError: /home/dpathirana/software/ICB-DCM/AMICI/python/sdist/amici/_amici.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cblas_dgemm
```

- I receive a similar error when trying to run the `AMICI/scripts/buildAmici.sh` script:
```
$ ./buildAmici.sh
-- Performing Test CUR_FLAG_SUPPORTED
-- Performing Test CUR_FLAG_SUPPORTED - Success
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- HDF5: Using hdf5 compiler wrapper to determine CXX configuration
-- Could NOT find Matlab (missing: Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR Matlab_MX_LIBRARY) (found version "NOTFOUND")
-- clang-format was not found
-- clang-tidy was not found
-- Found Boost: /opt/software/easybuild/software/Boost/1.71.0-gompi-2019b/lib/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components:  serialization
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dpathirana/software/ICB-DCM/AMICI/build
-- Found Git: /usr/bin/git (found version "1.8.3.1")
[  0%] Built target version
[ 15%] Built target amici
[ 15%] Performing build step for 'external_model_jakstat_adjoint'
[ 81%] Built target model_jakstat_adjoint
[ 85%] Linking CXX executable simulate_model_jakstat_adjoint
/opt/software/easybuild/software/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: error: cannot find -lcblas
/home/dpathirana/software/ICB-DCM/AMICI/src/cblas.cpp:27: error: undefined reference to 'cblas_dgemm'
/home/dpathirana/software/ICB-DCM/AMICI/src/cblas.cpp:36: error: undefined reference to 'cblas_dgemv'
/home/dpathirana/software/ICB-DCM/AMICI/src/cblas.cpp:41: error: undefined reference to 'cblas_daxpy'
collect2: error: ld returned 1 exit status
make[5]: *** [simulate_model_jakstat_adjoint] Error 1
make[4]: *** [CMakeFiles/simulate_model_jakstat_adjoint.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [tests/cpputest/external_model_jakstat_adjoint-prefix/src/external_model_jakstat_adjoint-stamp/external_model_jakstat_adjoint-build] Error 2
make[1]: *** [tests/cpputest/CMakeFiles/external_model_jakstat_adjoint.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by FFroehlich** [comment]
Looks like the same issue as #1038. Not sure whats up with anaconda and openblas. Using atlas instead of openblas instead should fix those issues (or you can try to find the right `BLAS_LIBS` and `BLAS_CFLAGS`). Not too familiar with anaconda, but maybe maintaining a `conda install` formula for amici makes sense and shouldn't be too much trouble?

**Comment by dweindl** [comment]
I find compiling Python extensions with anaconda is a giant pain in the ass. Always messes up include and linking directories. If you have cblas and hdf5 via `modules` and as anaconda packages, it sometimes happens that it uses includes from the one and libraries from the others. Best to use explicit locations via the environment variables @FFroehlich mentioned. In an HPC context, I would give the `modules` versions priority over the anaconda ones as they should have been optimized for the given system.

Can't provide more details without knowing more about the available cblas module.

**Comment by dweindl** [comment]
P.S.: Was the OpenBLAS module loaded when those errors occurred? 

> ImportError: /home/dpathirana/software/ICB-DCM/AMICI/python/sdist/amici/_amici.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cblas_dgemm

> /opt/software/easybuild/software/binutils/2.32-GCCcore-8.3.0/bin/ld.gold: error: cannot find -lcblas

Also note that `BLAS_CFLAGS` need to set for AMICI installation *and* for any model import/compilation.

**Comment by dilpath** [comment]
Thanks! AMICI compiles and I can run the example `model_steadystate_scaled.xml` script in the first post.

Thanks also to Bonna support, they suggested a similar solution:

> sorry for the late answer. Please try
> 
> export BLAS_LIBS="-lopenblas"
> 
> before running pip install.
> 
> If you are in contact with the maintainers, it could be very easily implemented here:
> 
> https://github.com/ICB-DCM/AMICI/blob/390305f98c96ea505cf52884991774e7dfefdeff/python/amici/setuptools.py#L28
> 
> e.g. by parsing pkgconfig for 'openblas' (which contains CBLAS).
---
However, I still receive the same errors for `AMICI/scripts/buildAmici.sh`, as described at the end of the first post. I guessed a solution... In `CMakeLists.txt`, I changed `-lcblas` to `-lopenblas` here:
https://github.com/ICB-DCM/AMICI/blob/390305f98c96ea505cf52884991774e7dfefdeff/CMakeLists.txt#L104

Now I can run `AMICI/scripts/buildAmici.sh`, `AMICI/scripts/installAmiciSource.sh`, and `AMICI/scripts/run-SBMLTestSuite.sh`

It seems to simulate the SBML test cases and produce correct simulation results (when I look inside `AMICI/tests/amici-semantic-results/`), but the test does not terminate correctly (error is below). It's a separate issue so this issue can be closed, unless you'd like to incorporate some of the edits described in this post.

```
$ ./scripts/run-SBMLTestsuite.sh 1
============================================== test session starts ===============================================
platform linux -- Python 3.7.3, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /home/dpathirana/software/ICB-DCM/AMICI/build/venv/bin/python
cachedir: .pytest_cache
rootdir: /home/dpathirana/software/ICB-DCM/AMICI, inifile: pytest.ini
plugins: forked-1.1.3, xdist-1.31.0
[gw0] linux Python 3.7.3 cwd: /home/dpathirana/software/ICB-DCM/AMICI
[gw1] linux Python 3.7.3 cwd: /home/dpathirana/software/ICB-DCM/AMICI
[gw2] linux Python 3.7.3 cwd: /home/dpathirana/software/ICB-DCM/AMICI
[gw3] linux Python 3.7.3 cwd: /home/dpathirana/software/ICB-DCM/AMICI
[gw0] Python 3.7.3 (default, Mar 27 2019, 22:11:17)  -- [GCC 7.3.0]
[gw1] Python 3.7.3 (default, Mar 27 2019, 22:11:17)  -- [GCC 7.3.0]
[gw2] Python 3.7.3 (default, Mar 27 2019, 22:11:17)  -- [GCC 7.3.0]
[gw3] Python 3.7.3 (default, Mar 27 2019, 22:11:17)  -- [GCC 7.3.0]
gw0 [1] / gw1 [1] / gw2 [1] / gw3 [1]
scheduling tests via LoadScheduling

tests/testSBMLSuite.py::test_sbml_testsuite_case[1] Fatal Python error: Segmentation fault

Thread 0x00007fe853c7e700 (most recent call first):
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 400 in read
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 432 in from_io
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 967 in _thread_receiver
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 220 in run
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 285 in _perform_spawn

Current thread 0x00007fe85b3bc740 (most recent call first):
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/python.py", line 184 in pytest_pyfunc_call
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/python.py", line 1479 in runtest
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/runner.py", line 135 in pytest_runtest_call
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/runner.py", line 217 in <lambda>
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/runner.py", line 244 in from_call
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/runner.py", line 217 in call_runtest_hook
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/runner.py", line 186 in call_and_report
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/runner.py", line 100 in runtestprotocol
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/runner.py", line 85 in pytest_runtest_protocol
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/xdist/remote.py", line 87 in run_one_test
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/xdist/remote.py", line 73 in pytest_runtestloop
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/main.py", line 247 in _main
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/main.py", line 191 in wrap_session
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/_pytest/main.py", line 240 in pytest_cmdline_main
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/manager.py", line 87 in <lambda>
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/xdist/remote.py", line 258 in <module>
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 1084 in executetask
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 220 in run
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 285 in _perform_spawn
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 267 in integrate_as_primary_thread
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 1060 in serve
  File "/home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/execnet/gateway_base.py", line 1554 in serve
  File "<string>", line 8 in <module>
  File "<string>", line 1 in <module>

[gw0] node down: Not properly terminated
[gw0] FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[1]

replacing crashed worker gw0
[gw4] linux Python 3.7.3 cwd: /home/dpathirana/software/ICB-DCM/AMICI
[gw4] Python 3.7.3 (default, Mar 27 2019, 22:11:17)  -- [GCC 7.3.0]
gw4 ok / gw1 [1] / gw2 [1] / gw3 [1]
==================================================== FAILURES ====================================================
_____________________________________________ tests/testSBMLSuite.py _____________________________________________
[gw0] linux -- Python 3.7.3 /home/dpathirana/software/ICB-DCM/AMICI/build/venv/bin/python
worker 'gw0' crashed while running 'tests/testSBMLSuite.py::test_sbml_testsuite_case[1]'
================================================ warnings summary ================================================
build/venv/lib/python3.7/site-packages/pysb/core.py:2231: 15 tests with warnings
  /home/dpathirana/software/ICB-DCM/AMICI/build/venv/lib/python3.7/site-packages/pysb/core.py:2231: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class ComponentSet(collections.Set, collections.Mapping, collections.Sequence):

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================================ short test summary info =============================================
FAILED tests/testSBMLSuite.py::test_sbml_testsuite_case[1]
======================================== 1 failed, 15 warnings in 15.29s =========================================
```
