### ISSUE TITLE
Unittests crashing with Intel compiler

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#1133]
Using icpc 2019.5.281
```
terminate called after throwing an instance of 'amici::AmiException'
  what():  Could not find parameter with specified id (p[\d]+)
```
in 
```
#0  0x00007ffff5b95f67 in raise () from /lib64/libc.so.6
#1  0x00007ffff5b9733a in abort () from /lib64/libc.so.6
#2  0x00007ffff61b61e5 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff61b3fd6 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff61b4021 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff61b4263 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x13d8b50 <typeinfo for amici::AmiException>, dest=0x4b7110 <amici::AmiException::~AmiException()>)
    at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:93
#6  0x0000000000512ffc in _INTERNALc1c64576::amici::setValueByIdRegex(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<double, std::allocator<double> >&, double, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, char const*) ()
#7  0x0000000000512a8f in amici::Model::setParametersByIdRegex(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double) ()
#8  0x000000000049d1f2 in TEST_model_testNameIdGetterSetter_Test::testBody() ()
```

**Comment by FFroehlich** [comment]
#754 strikes again?

**Comment by dweindl** [comment]
Didn't get to check in more detail, but also had that suspicion...

**Comment by dweindl** [comment]
> #754 strikes again?

The original issue seems to fixed. Now the workaround is broken. :)

**Comment by dweindl** [comment]
Done.
