### ISSUE TITLE
[python] add build script that allows "editable install"

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#368]
See 
https://pip.pypa.io/en/stable/reference/pip_install/#editable-installs
https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

**Comment by FFroehlich** [comment]
Theoretically should work via 
`pip3 install -e git+https://github.com/ICB-DCM/AMICI#egg=amici\&subdirectory=python/sdist`
but currently fails with 
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/ffroehlich/Documents/GitHub/src/amici/python/sdist/setup.py", line 350, in <module>
        main()
      File "/Users/ffroehlich/Documents/GitHub/src/amici/python/sdist/setup.py", line 344, in main
        'Topic :: Scientific/Engineering :: Bio-Informatics',
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/develop.py", line 138, in install_for_development
        self.run_command('build_ext')
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/ffroehlich/Documents/GitHub/src/amici/python/sdist/setup.py", line 192, in run
        libfilenames) == 1, "Found unexpected number of files: " % libfilenames
    AssertionError: Found unexpected number of files:
```
