### ISSUE TITLE
[python] Error for log10 transformed observables

### ISSUE THREAD

**Issue by LoosC** [ICB-DCM/AMICI#382]
When having an observable which is log10 transformed, e.g.

```xml
      <assignmentRule variable="STAT5_abs">
        <math xmlns="http://www.w3.org/1998/Math/MathML">
          <apply>
            <log/>
            <logbase>
              <cn type="integer"> 10 </cn>
            </logbase>
            <ci> STAT5 </ci>
          </apply>
        </math>
      </assignmentRule>
```
in sbml2amici the error occurs:

```
raise SBMLException('Encountered unsupported function in expression "' + str(math) + '"!')
amici.sbml_import.SBMLException: Encountered unsupported function in expression "scale*Subs(Derivative(log10(_xi_1), _xi_1), (_xi_1)
```

**Comment by dweindl** [comment]
Funny, log2 worked for me. This happens after using `amici.assignmentRules2observables`? Can you show the returned formula for this one?

**Comment by LoosC** [comment]
> Funny, log2 worked for me. This happens after using amici.assignmentRules2observables? 

Yes

> Can you show the returned formula for this one?

`Observables: {'STAT5_abs': 'log10(STAT5)'}`

And the full error message is then:
```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/amici/sbml_import.py", line 1254, in printWithException
    return self.Codeprinter.doprint(math)
  File "/anaconda3/lib/python3.6/site-packages/symengine/printing.py", line 14, in doprint
    return ccode(expr)
  File "symengine/lib/symengine_wrapper.pyx", line 3403, in symengine.lib.symengine_wrapper.ccode (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-3j7wscdz-build/build/lib.macosx-10.6-intel-3.6/symengine/lib/symengine_wrapper.cpp:95764)
RuntimeError: Not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/carolinloos/PhD/Software/AMICIGit/python/examples/20_benchmark_models/20_benchmark_models.py", line 82, in <module>
    observables=observables
  File "/anaconda3/lib/python3.6/site-packages/amici/sbml_import.py", line 251, in sbml2amici
    self.generateCCode()
  File "/anaconda3/lib/python3.6/site-packages/amici/sbml_import.py", line 878, in generateCCode
    self.writeFunctionFile(function)
  File "/anaconda3/lib/python3.6/site-packages/amici/sbml_import.py", line 989, in writeFunctionFile
    body = self.getFunctionBody(function)
  File "/anaconda3/lib/python3.6/site-packages/amici/sbml_import.py", line 1042, in getFunctionBody
    lines += self.getSymLines(symbol, variableName, 4)
  File "/anaconda3/lib/python3.6/site-packages/amici/sbml_import.py", line 1205, in getSymLines
    if not math == 0 else '' for index, math in enumerate(symbols)]
  File "/anaconda3/lib/python3.6/site-packages/amici/sbml_import.py", line 1205, in <listcomp>
    if not math == 0 else '' for index, math in enumerate(symbols)]
  File "/anaconda3/lib/python3.6/site-packages/amici/sbml_import.py", line 1256, in printWithException
    raise SBMLException('Encountered unsupported function in expression "' + str(math) + '"!')
amici.sbml_import.SBMLException: Encountered unsupported function in expression "Derivative(log10(STAT5), STAT5)"!

Process finished with exit code 1
```

So log10 is no known function there?

**Comment by dweindl** [comment]
Right. Need to check how to teach log10 as new function or how to tell libsbml to change output format.

For a quick workaround: 
``` 
import re
observables = { key: re.sub(r'(^|\W)log10\(', r'\1log(10, ', formula) for key, formula in observables.items() }
```

**Comment by FFroehlich** [comment]
could you please attach the sbml file where and loading script to reproduce this issue?

**Comment by LoosC** [comment]
And here are the corresponding files:

[reproduce_log10_error.zip](https://github.com/ICB-DCM/AMICI/files/2276967/reproduce_log10_error.zip)

**Comment by FFroehlich** [comment]
could not find a good way to fix this :(

libSBML only knows `log10`.
this would be straightforward to fix in `sympy` but with missing documentation and not fully supporting sympy features, I could not figure out how to do this in `symengine` :(

**Comment by dweindl** [comment]
The symengine documentation could definitely be improved...

At least as intermediary solution, the string replacement should be enough, though.

**Comment by FFroehlich** [comment]
The string replacement will fuck up any function definition that ends in log10, so it will probably need a bit more work

**Comment by dweindl** [comment]
I am quite sure I considered that and it does not. Do you have an example?

**Comment by FFroehlich** [comment]
a right, did not notice the `(^|\W)` before, should be fine I guess.

**Comment by dweindl** [comment]
(For reference: #412)
