### ISSUE TITLE
[python] model compilation failes due to swig?

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/AMICI#389]
See https://travis-ci.com/ICB-DCM/pyPESTO/builds/80689912.

I cannot reproduce this locally.

```
error: command 'swig' failed with exit status 1
E
======================================================================
ERROR: runTest (__main__.OptimizerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test_sbml_conversion.py", line 22, in runTest
    objective, model = load_model_objective(example)
  File "./test/test_sbml_conversion.py", line 90, in load_model_objective
    verbose=False)
  File "/home/travis/.local/lib/python3.6/site-packages/amici/sbml_import.py", line 286, in sbml2amici
    self.compileCCode(verbose)
  File "/home/travis/.local/lib/python3.6/site-packages/amici/sbml_import.py", line 965, in compileCCode
    check=True)
  File "/opt/pyenv/versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/pyenv/versions/3.6/bin/python3', '/home/travis/build/ICB-DCM/pyPESTO/example/conversion_reaction/setup.py', '--quiet', 'build_ext', '--build-lib=/home/travis/build/ICB-DCM/pyPESTO/example/conversion_reaction']' returned non-zero exit status 1.
```

**Comment by yannikschaelte** [comment]
I have the same error on a local linux installation. i guess it will occur when you have the latest versions of all python modules installed, provided something broke there recently.

**Comment by paulflang** [comment]
This issue may still be present in the light version of AMICI:

```pip3 install --install-option --no-clibs amici```

```
root@4760652c400e:~/host/Documents/Project07_Parameter Fitting/benchmark/inputs/intermediate_models/project/models# python3 sbml2ami_mex.py 
/usr/local/lib/python3.7/site-packages/amici/sbml_import.py:263: UserWarning: AMICI C++ extensions have not been built. Generated model code, but unable to compile.
  warnings.warn('AMICI C++ extensions have not been built. '
error: command 'swig' failed with exit status 1

Traceback (most recent call last):
  File "sbml2ami_mex.py", line 38, in <module>
    sigmas=sigmas
  File "/usr/local/lib/python3.7/site-packages/amici/sbml_import.py", line 265, in sbml2amici
    exporter.compileModel()
  File "/usr/local/lib/python3.7/site-packages/amici/ode_export.py", line 1906, in compileModel
    self._compileCCode(compiler=self.compiler, verbose=self.verbose)
  File "/usr/local/lib/python3.7/site-packages/amici/ode_export.py", line 1990, in _compileCCode
    check=True)
  File "/usr/local/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '/root/host/Documents/Project07_Parameter Fitting/benchmark/inputs/intermediate_models/project/models/model_steadystate_scaled/setup.py', '--quiet', 'build_ext', '--build-lib=/root/host/Documents/Project07_Parameter Fitting/benchmark/inputs/intermediate_models/project/models/model_steadystate_scaled']' returned non-zero exit status 1.
root@4760652c400e:~/host/Documents/Project07_Parameter Fitting/benchmark/inputs/intermediate_models/project/models#
```
[sbml2ami_mex.txt](https://github.com/ICB-DCM/AMICI/files/4064803/sbml2ami_mex.txt)

**Comment by dweindl** [comment]
@paulflang : Adding `compile=False` to 

> sbml_importer.sbml2amici(model_name, 
                         model_output_dir, 
                         verbose=False,
                         observables=observables,
                         constantParameters=constantParameters,
                         sigmas=sigmas
                         )

Should fix this.

**Comment by paulflang** [comment]
@dweindl :
unfortunately, this resulted in a different error:
```
root@4760652c400e:~/host/Documents/Project07_Parameter Fitting/benchmark/inputs/intermediate_models/project/models# python3 sbml2ami_mex.py 
Traceback (most recent call last):
  File "sbml2ami_mex.py", line 43, in <module>
    model_module = importlib.import_module(model_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/host/Documents/Project07_Parameter Fitting/benchmark/inputs/intermediate_models/project/models/model_steadystate_scaled/model_steadystate_scaled/__init__.py", line 14, in <module>
    from model_steadystate_scaled._model_steadystate_scaled import *
ModuleNotFoundError: No module named 'model_steadystate_scaled._model_steadystate_scaled'
```
The only module I can see is ```model_steadystate_scaled.model_steadystate_scaled```, i.e  without the underscore. So I prefixed an underscore to the corresponding folder and ran:

```
In [1]: import importlib                                                                                 

In [2]: model_name = 'model_steadystate_scaled'                                                          

In [3]: model_output_dir = model_name                                                                    

In [4]: model_module = importlib.import_module(model_name)                                               

In [5]: import libsbml 
   ...: import importlib 
   ...: import amici 
   ...: import os 
   ...: import sys 
   ...: import numpy as np 
   ...: import matplotlib.pyplot as plt                                                                  

In [6]: model = model_module.getModel()                                                                  
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-726769f3980b> in <module>
----> 1 model = model_module.getModel()

AttributeError: module 'model_steadystate_scaled' has no attribute 'getModel'
```
Would very much appreciate your help for a (workaround) solution. The background why I am trying all this, is to test the algorithms from the paper "Benchmarking optimization methods for parameter estimation in large kinetic models" on one of my models. However, I failed to convert an sbml file into a MATLAB .mex file using amiwrap.m in Matlab 2019b (because this is not longer supported) 2017b.

Thanks,
Paul

**Comment by dweindl** [comment]
Hi Paul,

As you want to generate a mex file, you don't need to build the python module. This is why you installed AMICI with `--no-clibs` and imported the model with `compile=False`, which tells AMICI to not build the python module. Therefore, the importing the non-existent module fails.

To generate the mex file, you stop after `sbml_importer.sbml2amici`. In the generated directory, there is a single `.m` file which you call from matlab. This will generate the mex file for this model.

Hope this helps.

**Comment by paulflang** [comment]
I see. This could be a nice workaround indeed. Unfortunately, running compileMexFile.m in Matlab on Windows currently also fails:
```
>> compileMexFile
The current working directory is:
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\benchmark\inputs\intermediate_models\project\models\model_steadystate_scaled
Error using mex
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter
Fitting\benchmark\inputs\intermediate_models\project\models\model_steadystate_scaled\- not found; check that you are in the
correct current folder, and check the spelling of 'C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter
Fitting\benchmark\inputs\intermediate_models\project\models\model_steadystate_scaled\-'.

Error in compileAMICIDependencies (line 51)
        eval(['mex ' DEBUG ' ' COPT ' -c -outdir ' ...

Error in amimodel.compileAndLinkModel (line 65)
    [objectsstr, includesstr] = compileAMICIDependencies(dependencyPath, objectFolder, objectFileSuffix, COPT, DEBUG);

Error in compileMexFile (line 9)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
```

The code in the compile file is:
```
disp('The current working directory:')
disp(pwd())

modelName = 'model_steadystate_scaled';
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
amimodel.generateMatlabWrapper(3, 6, 8, 1, 0, 0, [], ...
            ['simulate_' modelName '.m'], modelName, 'lin', 1, 1);
```

**Comment by dweindl** [comment]
Quick guess would be that this is due to blanks in the file name. This should be handled properly by AMICI. But for a quick test, can you move the generated directory to location without blanks in the path an rerun `compileMexFile`?

**Comment by paulflang** [comment]
This does not work either. I do not know why there is a dash suffixed to the path. Anyway, the output is:
```
>> compileMexFile
The current working directory:
C:\Users\wolf5212\Desktop\model_steadystate_scaled
Error using mex
C:\Users\wolf5212\Desktop\model_steadystate_scaled\- not found; check that you are in the correct current folder, and check the
spelling of 'C:\Users\wolf5212\Desktop\model_steadystate_scaled\-'.

Error in compileAMICIDependencies (line 51)
        eval(['mex ' DEBUG ' ' COPT ' -c -outdir ' ...

Error in amimodel.compileAndLinkModel (line 65)
    [objectsstr, includesstr] = compileAMICIDependencies(dependencyPath, objectFolder, objectFileSuffix, COPT, DEBUG);

Error in compileMexFile (line 9)
amimodel.compileAndLinkModel(modelName, pwd(), [], [], [], []);
```

**Comment by dweindl** [comment]
Thanks for testing. Ah, just noticed that it is not about the model, but the dependencies. So it is about the blanks in the path of AMICI. Will try to fix it (#910).

**Comment by paulflang** [comment]
@dweindl : thanks a lot!

**Comment by dweindl** [comment]
@paulflang : You can try again with AMICI from https://github.com/ICB-DCM/AMICI/tree/fix_910_matlab_blanks . Will probably take a bit until this makes it to `master`.

**Comment by paulflang** [comment]
I just replaced the master branch code in ```AMICI/matlab/auxiliary/compileAMICIDependencies.m``` with the one in the branch you suggested, but still got the same error:
```
>> compileMexFile
AMICI base files | Error using mex
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter
Fitting\benchmark\inputs\intermediate_models\project\models\model_steadystate_scaled\- not found; check that you are in the correct
current folder, and check the spelling of 'C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter
Fitting\benchmark\inputs\intermediate_models\project\models\model_steadystate_scaled\-'.

Error in amimodel.compileAndLinkModel>compileAmiciBase (line 206)
        eval(['mex ' DEBUG COPT ' -c -outdir ' objectFolder ...

Error in amimodel.compileAndLinkModel (line 69)
    [objectStrAmici] = compileAmiciBase(amiciRootPath, objectFolder, objectFileSuffix, includesstr, DEBUG, COPT);

Error in compileMexFile (line 6)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
```

**Comment by dweindl** [comment]
You also have to replace `matlab/@amimodel/compileAndLinkModel.m` (See https://github.com/ICB-DCM/AMICI/pull/911/files for changes)

**Comment by paulflang** [comment]
Oh, sorry for missing that. Now I get a different error (probably a `/` vs. `\` confusion:
```
>> compileMexFile
AMICI base files | Building with 'MinGW64 Compiler (C++)'.
Error using mex
In file included from C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter
Fitting\AMICI\include/amici/edata.h:5:0,
                 from C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter
                 Fitting\AMICI\include/amici/amici.h:6,
                 from C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\amici.cpp:6:
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\include/amici/vector.h:11:28: fatal error:
gsl/gsl-lite.hpp: No such file or directory
 #include <gsl/gsl-lite.hpp>
                            ^
compilation terminated.


Error in amimodel.compileAndLinkModel>compileAmiciBase (line 206)
        eval(['mex ' DEBUG COPT ' -c -outdir "' objectFolder '" ' ...

Error in amimodel.compileAndLinkModel (line 69)
    [objectStrAmici] = compileAmiciBase(amiciRootPath, objectFolder, objectFileSuffix, includesstr, DEBUG, COPT);

Error in compileMexFile (line 6)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
```

**Comment by dweindl** [comment]
Hmm... Can you add 
```
        disp(['mex ' DEBUG COPT ' -c -outdir "' objectFolder '" ' ...
            includesstr ' ' sourceStr])
```

before amimodel.compileAndLinkModel>compileAmiciBase (line 206) and show the output?

**Comment by paulflang** [comment]
Sure. The output is:
```
>> compileMexFile
AMICI base files | mex COPTIMFLAGS=' -DNDEBUG' CXXFLAGS='$CXXFLAGS -std=c++0x' -c -outdir "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\models\mexw64\2019b\g0x2B0x2B_x86_64_posix_seh_rev20x2C_Built_by_MinGW_W64_project_\release"  -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\ThirdParty\sundials\include" -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\ThirdParty\sundials\src" -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI" -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src" -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\include" -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\ThirdParty\SuiteSparse\KLU\Include" -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\ThirdParty\SuiteSparse\AMD\Include" -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\ThirdParty\SuiteSparse\COLAMD\Include" -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\ThirdParty\SuiteSparse\BTF\Include" -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\ThirdParty\SuiteSparse\SuiteSparse_config" -I"" -I"C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\ThirdParty\gsl"  "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\amici.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\symbolic_functions.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\spline.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\edata.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\rdata.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\exception.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\interface_matlab.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\misc.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver_cvodes.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\solver_idas.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\model.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\model_ode.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\model_dae.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\returndata_matlab.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\forwardproblem.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\steadystateproblem.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\backwardproblem.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\newton_solver.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\abstract_model.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\sundials_matrix_wrapper.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\sundials_linsol_wrapper.cpp" "C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\vector.cpp"
Building with 'MinGW64 Compiler (C++)'.
Error using mex
In file included from C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter
Fitting\AMICI\include/amici/edata.h:5:0,
                 from C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter
                 Fitting\AMICI\include/amici/amici.h:6,
                 from C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\src\amici.cpp:6:
C:\Users\wolf5212\OneDrive - Nexus365\DPhil Project\Project07_Parameter Fitting\AMICI\include/amici/vector.h:11:28: fatal error:
gsl/gsl-lite.hpp: No such file or directory
 #include <gsl/gsl-lite.hpp>
                            ^
compilation terminated.


Error in amimodel.compileAndLinkModel>compileAmiciBase (line 208)
        eval(['mex ' DEBUG COPT ' -c -outdir "' objectFolder '" ' ...

Error in amimodel.compileAndLinkModel (line 69)
    [objectStrAmici] = compileAmiciBase(amiciRootPath, objectFolder, objectFileSuffix, includesstr, DEBUG, COPT);

Error in compileMexFile (line 6)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
```

**Comment by dweindl** [comment]
Thanks. Should work with the updated `matlab/@amimodel/compileAndLinkModel.m` from https://github.com/ICB-DCM/AMICI/tree/fix_910_matlab_blanks.

**Comment by paulflang** [comment]
I think this link is broken. I can also no longer find the 'fix_910_matlab_blanks' branch to test this.

**Comment by dweindl** [comment]
I updated it just after posting. I guess you got the original one via email. https://github.com/ICB-DCM/AMICI/tree/develop

**Comment by paulflang** [comment]
OK. I used this link now. I am afraid it still does not work:
```
>> compileMexFile
AMICI base files | Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Error using CalcMD5 (line 70)
Cannot find MEX script.

Error in amimodel.compileAndLinkModel>getFileHash (line 244)
    hash = CalcMD5(file,'File','hex');

Error in amimodel.compileAndLinkModel>updateFileHash (line 256)
    hash = getFileHash(fullfile(fileFolder,filename));

Error in amimodel.compileAndLinkModel>updateFileHashSource (line 250)
        updateFileHash(sourceFolder,objectFolder,fileName);

Error in amimodel.compileAndLinkModel>@(x)updateFileHashSource(amiciSourcePath,objectFolder,x) (line 211)
        cellfun(@(x) updateFileHashSource(amiciSourcePath, objectFolder, x), sourcesForRecompile);

Error in amimodel.compileAndLinkModel>compileAmiciBase (line 211)
        cellfun(@(x) updateFileHashSource(amiciSourcePath, objectFolder, x), sourcesForRecompile);

Error in amimodel.compileAndLinkModel (line 72)
    [objectStrAmici] = compileAmiciBase(amiciRootPath, objectFolder, objectFileSuffix, includesstr, DEBUG, COPT);

Error in compileMexFile (line 6)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
```

**Comment by dweindl** [comment]
Will look into that tomorrow. It's possible the executable is created in the wrong place when called from that python import script. You can trying running one of the matlab examples e.g. `matlab/examples/example_steadystate/example_steadystate.m` first and then try `compileMexFile` again.

**Comment by paulflang** [comment]
Thanks a lot. I'll call it a day, too. FYI, I could not run `matlab/examples/example_steadystate/example_steadystate.m` because I am using Matlab 2019b.
```
>> compileMexFile
AMICI base files | Building with 'MinGW64 Compiler (C++)'.
MEX completed successfully.
Error using CalcMD5 (line 70)
Cannot find MEX script.

Error in amimodel.compileAndLinkModel>getFileHash (line 244)
    hash = CalcMD5(file,'File','hex');

Error in amimodel.compileAndLinkModel>updateFileHash (line 256)
    hash = getFileHash(fullfile(fileFolder,filename));

Error in amimodel.compileAndLinkModel>updateFileHashSource (line 250)
        updateFileHash(sourceFolder,objectFolder,fileName);

Error in amimodel.compileAndLinkModel>@(x)updateFileHashSource(amiciSourcePath,objectFolder,x) (line 211)
        cellfun(@(x) updateFileHashSource(amiciSourcePath, objectFolder, x), sourcesForRecompile);

Error in amimodel.compileAndLinkModel>compileAmiciBase (line 211)
        cellfun(@(x) updateFileHashSource(amiciSourcePath, objectFolder, x), sourcesForRecompile);

Error in amimodel.compileAndLinkModel (line 72)
    [objectStrAmici] = compileAmiciBase(amiciRootPath, objectFolder, objectFileSuffix, includesstr, DEBUG, COPT);

Error in compileMexFile (line 6)
amimodel.compileAndLinkModel(modelName, '', [], [], [], []);
 
>> example_steadystate
Error using amiwrap (line 16)
MATLAB R2018a or higher is currently not supported (see https://github.com/ICB-DCM/AMICI/issues/307)

Error in example_steadystate (line 7)
    amiwrap('model_steadystate','model_steadystate_syms',exdir)
```

**Comment by dweindl** [comment]
> FYI, I could not run `matlab/examples/example_steadystate/example_steadystate.m` because I am using Matlab 2019b.

Right. 

See #914.
