### ISSUE TITLE
pkg-config seems still to be used

### ISSUE THREAD

**Issue by JanHasenauer** [ICB-DCM/AMICI#455]
```
bash-3.2$ CFLAGS="-stdlib=libc++" CC=clang CXX=clang pip3 install --verbose amici
Collecting amici
  1 location(s) to search for versions of amici:
  * https://pypi.python.org/simple/amici/
  Getting page https://pypi.python.org/simple/amici/
  Looking up "https://pypi.python.org/simple/amici/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/amici/" in the cache
  Current age based on date: 611
  Freshness lifetime from request max-age: 600
  Starting new HTTPS connection (1): pypi.org
  https://pypi.org:443 "GET /simple/amici/ HTTP/1.1" 200 2649
  Updating cache with response from "https://pypi.org/simple/amici/"
  Caching due to etag
  Analyzing links from page https://pypi.org/simple/amici/
    Found link https://files.pythonhosted.org/packages/1c/10/4edb06ac27cc0f616d9dba549e842e512c18b25475e54abe0d592938ee28/amici-0.6a1.tar.gz#sha256=fd4c5f3076163ca48ae7fe090c20f5e3f5000bb525048daec18c820441f26efa (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a1
    Found link https://files.pythonhosted.org/packages/26/60/60665d4cf436da9ab4f6212a14a73989b1751101b54d4337043eeae05cd0/amici-0.6a2.tar.gz#sha256=02dfb15605c8e23db83a672d0140edf3f0cfec079a8ac5a7cf00277b6fb22d98 (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a2
    Found link https://files.pythonhosted.org/packages/6d/7d/93eb4a3f4f90d107c424f01107f5108d6b61f84361604f0d590cbb3e75ab/amici-0.6a3.tar.gz#sha256=bd43c7b71cb48f72e15e3828dc0fbdc6dab861dbe694dc23c9d924619fc3b44b (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a3
    Found link https://files.pythonhosted.org/packages/a6/fb/cb73170dc75e00d452156975f5a3ce076d0de3cfd15cee85eda44d92f8cf/amici-0.6a4.tar.gz#sha256=1b5fec5338a4e02f9faf0208c3d45a5fd76fa3a37b16ce0b18b50f92c9ada4ef (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a4
    Found link https://files.pythonhosted.org/packages/52/9f/c0d36a8938643e03ff65fca2ccb31f018463c01e802afed27f8f28cf92e0/amici-0.6a5.tar.gz#sha256=831fbefa5cf696c6ccdfdcb41e3157dc7fff2f6e2748d79e2c14cf52fad73106 (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a5
    Found link https://files.pythonhosted.org/packages/14/85/6960d6fbbaf3f4c6b22b32dc694ddb58737057ee02b91ff0bd4ed908e8ef/amici-0.6a6.tar.gz#sha256=447855468fa387be3a32438fcf7d02c23ecfc0f0348749f2a2f8543b325ad480 (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a6
    Found link https://files.pythonhosted.org/packages/90/7a/e2c140d61217b89efd6107472461f2b3c2e389c2b775914859f3e79adb5e/amici-0.6a7.tar.gz#sha256=4aa28113358dff251de2d4327fc63beb405e5f540e3e159b0dda3f79008a7e85 (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a7
    Found link https://files.pythonhosted.org/packages/41/5b/400938148b643df579bc112cdf62d8ac3b0ef7af3852ad7ff242cb016a7e/amici-0.6a8.tar.gz#sha256=a19d119d60240ba826a38d59555e096acb3d1efd9fcd9e683c2d3ecd0b739bd4 (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a8
    Found link https://files.pythonhosted.org/packages/a9/56/eb31ca58d8ad2737b0dc534e838ff2fd4c1c515133915fa81e6fe61fafe1/amici-0.6a9.tar.gz#sha256=2333e598d6f76659d6b8bdcb2e09efaae3f2d9adca5ce8d345d6a4da9b3b21ca (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a9
    Found link https://files.pythonhosted.org/packages/22/8c/4fdfb6669e02d2ebb7d5c2abe0ce0e29ed1ad89fe36db0ab45292a7a57ae/amici-0.6a10.tar.gz#sha256=f990170c342904521e891f939996cd8570f01f54ec93431704f1968300c342ee (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a10
    Found link https://files.pythonhosted.org/packages/f7/4d/c2fafed9d87699205cfa1e66cb0021cb044018da0c8128264bb641211fcb/amici-0.6a11.tar.gz#sha256=95534eeaab2bc06604491bf2f1c0caec9e8ab8a6875465ef00c553746156de5d (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a11
    Found link https://files.pythonhosted.org/packages/a6/9b/3301dd08da0516a49022850d6dc3f00e6aa04404553841c186a28939c43c/amici-0.6a12.tar.gz#sha256=fd509770bf61664e7aa3d8c3820bd789670fdf02283b3c0ddbe2cebb8a7cf6ec (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a12
    Found link https://files.pythonhosted.org/packages/76/2e/accc5c6e610a6813b1fa645d76cdf627c3dd61b454c5919079444363885c/amici-0.6a14.tar.gz#sha256=fec921c4299cbb1add207a36bc85e173454737c2d33d893b0e225b6e83def02d (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a14
    Found link https://files.pythonhosted.org/packages/62/93/0a5efa2047010c03d23b7667148b36c440b9c021d26e1fd340e6ac4f4d76/amici-0.6a15.tar.gz#sha256=94222bb9cbc12091fb1dc40e7328439a34ef094368f9a5cb9617dc229315e4f7 (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.6a15
    Found link https://files.pythonhosted.org/packages/55/1c/204a6e616a9f09d192ad83575c7b042104749f3d49e70fbc049bc4b79480/amici-0.7a1.tar.gz#sha256=ebdea2a4e9814993560b92a5a21956390ff8b61d8f965ba88551e33cbbf3bc7c (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7a1
    Found link https://files.pythonhosted.org/packages/f7/d7/b854545d0bc67a300c706c214658f33b6641041eba552553bcfcbc5221ab/amici-0.7a2.tar.gz#sha256=25592357bdf6def33dd8111e90afcaf087db3547cd20465fa4f17e38c8705405 (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7a2
    Found link https://files.pythonhosted.org/packages/16/6c/789805e1f884b84c59b749d8c1be5b7fdcc1eda6a4f8f1b858ebc48181c5/amici-0.7.2.tar.gz#sha256=1cb51c7a8c6921a50a2eb5a35dc24475a55e4d81ff6fb42e59254e80a86c75aa (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.2
    Found link https://files.pythonhosted.org/packages/4e/bf/bbbe2c03bf87ad5d06860f211f4b02f89706b592fe4c461a3da50c39daf1/amici-0.7.3.tar.gz#sha256=4185d3ee123999be02ff7760c7275e828c0576e515519aaf8b7fac01dc68508e (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.3
    Found link https://files.pythonhosted.org/packages/24/1c/2b84c7c823c30a1ccd6c8f0e294e2a81464c73d0d435ad33f753a68dfeca/amici-0.7.4.tar.gz#sha256=c54ed874a84ad5c61ad77fcfcd9ed9fb39d8f6bed5fe0f0e5f577398297c3b0d (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.4
    Found link https://files.pythonhosted.org/packages/b5/70/d4063f08ba22ad36790320dfcba02a946fe48c3608af0b8a814a02b46a3f/amici-0.7.5.tar.gz#sha256=0a888a5d6d23f764d00f6edf755213633eba4194b02d085d470b5610afb1a92a (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.5
    Found link https://files.pythonhosted.org/packages/c6/29/42adab3dd902fe3a32b7a773b3e0a9f2c21727108b6107723b4bdd728f60/amici-0.7.5.post1.tar.gz#sha256=bd87c3e82f42d7c046b23fefaad53e18c1e533dd9fec199236930f44587342f1 (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.5.post1
    Found link https://files.pythonhosted.org/packages/b5/7e/7f99f7a2d66ca04ce637426cffa55aa14f165abc8c35817615a1d75ebfb0/amici-0.7.6.tar.gz#sha256=89bc62bc0cdec87a7f59a33737445cbcfc8cec73fa49648ed29898b9343ea090 (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.6
    Found link https://files.pythonhosted.org/packages/9e/5f/e5deef60c026463912e28dbeaa2e44cbfbdb9da77407dce26704248bc0ae/amici-0.7.7.tar.gz#sha256=2f2e413d023aed2e8ae43112eb2203244b2742bad568d59e3f830291a16991cf (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.7
    Found link https://files.pythonhosted.org/packages/bc/12/ef381ae2c598313d39c14e5278aee81501b9e0f81d15b0ef0e2734dcd5ba/amici-0.7.8.tar.gz#sha256=57da753dc43b721659110535db91a075732267d3507c4e0285f6682da3882eec (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.8
    Found link https://files.pythonhosted.org/packages/90/3f/097c9b536560d229bfd9acb4fe7f347ecf67948aff07a28b0ee05602fa66/amici-0.7.9.tar.gz#sha256=30f060fe4882ab295cde44629c9af6647037e4fb4ba38f3d9da7a18637c491cf (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.9
    Found link https://files.pythonhosted.org/packages/da/86/6958a6bb375fbf17fe2d7ddcd1fd25e888f0180d2a38de83bb68f169f1ac/amici-0.7.10.tar.gz#sha256=5d55ba4b3aecec63d573b49759863020f23af44bcf6df85f0e98e9b5e56f7bec (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.10
    Found link https://files.pythonhosted.org/packages/d4/e3/1ede675f436b6d2d223e5e615841955c6ec36c6a37e7b07b80448a320230/amici-0.7.11.tar.gz#sha256=32f5d9cc4ddb502b575cabdf22007ad01e41d1268b4496ea8f84cb08e2cdef70 (from https://pypi.org/simple/amici/) (requires-python:>=3), version: 0.7.11
  Using version 0.7.11 (newest of versions: 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.5.post1, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.7.10, 0.7.11)
  Looking up "https://files.pythonhosted.org/packages/d4/e3/1ede675f436b6d2d223e5e615841955c6ec36c6a37e7b07b80448a320230/amici-0.7.11.tar.gz" in the cache
  Current age based on date: 31282
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 31282
  Using cached https://files.pythonhosted.org/packages/d4/e3/1ede675f436b6d2d223e5e615841955c6ec36c6a37e7b07b80448a320230/amici-0.7.11.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/d4/e3/1ede675f436b6d2d223e5e615841955c6ec36c6a37e7b07b80448a320230/amici-0.7.11.tar.gz#sha256=32f5d9cc4ddb502b575cabdf22007ad01e41d1268b4496ea8f84cb08e2cdef70 (from https://pypi.org/simple/amici/) (requires-python:>=3)
  Running setup.py (path:/private/var/folders/4j/2xyqzc0j33b6g1ksp9pphynm0000gp/T/pip-build-g2e7piyp/amici/setup.py) egg_info for package amici
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkgconfig/pkgconfig.py", line 60, in _wrapper
        return func(*args, **kwargs)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkgconfig/pkgconfig.py", line 89, in exists
        return call(cmd) == 0
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 267, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'pkg-config': 'pkg-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4j/2xyqzc0j33b6g1ksp9pphynm0000gp/T/pip-build-g2e7piyp/amici/setup.py", line 43, in <module>
        blaspkgcfg = getBlasConfig()
      File "/private/var/folders/4j/2xyqzc0j33b6g1ksp9pphynm0000gp/T/pip-build-g2e7piyp/amici/amici/setuptools.py", line 40, in getBlasConfig
        if pkgconfig.exists('cblas'):
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkgconfig/pkgconfig.py", line 62, in _wrapper
        raise EnvironmentError("pkg-config is probably not installed. Could not run pkg-config: %r"%e)
    OSError: pkg-config is probably not installed. Could not run pkg-config: FileNotFoundError(2, "No such file or directory: 'pkg-config'")
Cleaning up...
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4j/2xyqzc0j33b6g1ksp9pphynm0000gp/T/pip-build-g2e7piyp/amici/
Exception information:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/req/req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, incall_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4j/2xyqzc0j33b6g1ksp9pphynm0000gp/T/pip-build-g2e7piyp/amici/
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by FFroehlich** [comment]
pkg-config is the default way of figuring out where other c/c++ libraries are located. I don't think we can or want to remove that dependency anytime soon.

**Comment by dweindl** [comment]
We wanted to make it at least optional, since it was not working so convincingly
