### ISSUE TITLE
Python ImportError when running scripts/buildAll.sh

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#457]
```
[100%] Creating sdist for AMICI base python package
Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    from amici.setuptools import (
  File "/home/dweindl/src/AMICI-devel/python/sdist/amici/__init__.py", line 62, in <module>
    from .numpy import rdataToNumPyArrays, edataToNumPyArrays
  File "/home/dweindl/src/AMICI-devel/python/sdist/amici/numpy.py", line 1, in <module>
    from amici import stdVec2ndarray
ImportError: cannot import name 'stdVec2ndarray'
```

Hint: only import `if has_clibs:`

**Comment by dweindl** [comment]
Problem only arises when `python/sdist/` contains files from previous build which will lead to `has_clibs == true`.

**Comment by dweindl** [comment]
This is only an issue when new functions from the swig interface are imported somewhere. Prevent by deleting `python/sdist/amici/amici*`. Not sure how to handle that better.

**Comment by dweindl** [comment]
TODO: Make sure that `my_sdist` in `setup.py` deletes all SWIG files *after* packaging (specifically:  amici.py amici_without_hdf5.py amici_wrap.cxx amici_wrap_without_hdf5.cxx)
