### ISSUE TITLE
Error in handling of SBML piecewise(): Second argument must be a Boolean, not `xor`

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/AMICI#771]
```
======================================================================
ERROR: test_sbml_testsuite (__main__.TestAmiciSBMLTestSuite) (testId=201)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/testSBMLSuite.py", line 34, in test_sbml_testsuite
    self.run_sbml_testsuite_case(get_test_str(testId))
  File "./tests/testSBMLSuite.py", line 45, in run_sbml_testsuite_case
    model, solver, wrapper = compile_model(current_test_path, test_id)
  File "./tests/testSBMLSuite.py", line 147, in compile_model
    wrapper.sbml2amici(model_name, output_dir=model_dir)
  File "/home/icb/daniel.weindl/src/AMICI/python/sdist/amici/sbml_import.py", line 242, in sbml2amici
    self.processSBML(constantParameters)
  File "/home/icb/daniel.weindl/src/AMICI/python/sdist/amici/sbml_import.py", line 284, in processSBML
    self.processReactions()
  File "/home/icb/daniel.weindl/src/AMICI/python/sdist/amici/sbml_import.py", line 666, in processReactions
    symMath = _parse_special_functions(symMath)
  File "/home/icb/daniel.weindl/src/AMICI/python/sdist/amici/sbml_import.py", line 1218, in _parse_special_functions
    return sp.Piecewise(*grouper(args, 2, True))
  File "/home/icb/daniel.weindl/src/AMICI/build/venv/lib64/python3.6/site-packages/sympy/functions/elementary/piecewise.py", line 134, in __new__
    pair = ExprCondPair(*getattr(ec, 'args', ec))
  File "/home/icb/daniel.weindl/src/AMICI/build/venv/lib64/python3.6/site-packages/sympy/functions/elementary/piecewise.py", line 35, in __new__
    not `%s`''' % func_name(cond)))
TypeError:
Second argument must be a Boolean, not `xor`
```
and
```
======================================================================
ERROR: test_sbml_testsuite (__main__.TestAmiciSBMLTestSuite) (testId=279)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/testSBMLSuite.py", line 34, in test_sbml_testsuite
    self.run_sbml_testsuite_case(get_test_str(testId))
  File "./tests/testSBMLSuite.py", line 45, in run_sbml_testsuite_case
    model, solver, wrapper = compile_model(current_test_path, test_id)
  File "./tests/testSBMLSuite.py", line 147, in compile_model
    wrapper.sbml2amici(model_name, output_dir=model_dir)
  File "/home/icb/daniel.weindl/src/AMICI/python/sdist/amici/sbml_import.py", line 242, in sbml2amici
    self.processSBML(constantParameters)
  File "/home/icb/daniel.weindl/src/AMICI/python/sdist/amici/sbml_import.py", line 284, in processSBML
    self.processReactions()
  File "/home/icb/daniel.weindl/src/AMICI/python/sdist/amici/sbml_import.py", line 666, in processReactions
    symMath = _parse_special_functions(symMath)
  File "/home/icb/daniel.weindl/src/AMICI/python/sdist/amici/sbml_import.py", line 1218, in _parse_special_functions
    return sp.Piecewise(*grouper(args, 2, True))
  File "/home/icb/daniel.weindl/src/AMICI/build/venv/lib64/python3.6/site-packages/sympy/functions/elementary/piecewise.py", line 134, in __new__
    pair = ExprCondPair(*getattr(ec, 'args', ec))
  File "/home/icb/daniel.weindl/src/AMICI/build/venv/lib64/python3.6/site-packages/sympy/functions/elementary/piecewise.py", line 35, in __new__
    not `%s`''' % func_name(cond)))
TypeError:
Second argument must be a Boolean, not `xor`
```

**Comment by paulstapor** [comment]
somewhat my job...

**Comment by dweindl** [comment]
FYI: For testing, on #789 you can now simply run `scripts/run-SBMLTestsuite.sh 201,279` to run only the affected cases.

**Comment by dweindl** [comment]
One step further, now:
```
======================================================================
ERROR: test_sbml_testsuite (__main__.TestAmiciSBMLTestSuite) (testId=201)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/testSBMLSuite.py", line 74, in test_sbml_testsuite
    self.run_sbml_testsuite_case(get_test_str(testId))
  File "./tests/testSBMLSuite.py", line 85, in run_sbml_testsuite_case
    model, solver, wrapper = compile_model(current_test_path, test_id)
  File "./tests/testSBMLSuite.py", line 189, in compile_model
    wrapper.sbml2amici(model_name, output_dir=model_dir)
  File "/home/dweindl/src/AMICI-devel/python/sdist/amici/sbml_import.py", line 237, in sbml2amici
    self.processSBML(constantParameters)
  File "/home/dweindl/src/AMICI-devel/python/sdist/amici/sbml_import.py", line 279, in processSBML
    self.processReactions()
  File "/home/dweindl/src/AMICI-devel/python/sdist/amici/sbml_import.py", line 661, in processReactions
    symMath = _parse_special_functions(symMath)
  File "/home/dweindl/src/AMICI-devel/python/sdist/amici/sbml_import.py", line 1221, in _parse_special_functions
    return sp.Piecewise(*grouper(args, 2, True))
  File "/home/dweindl/src/AMICI-devel/build/venv/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 143, in __new__
    r = cls.eval(*newargs)
  File "/home/dweindl/src/AMICI-devel/build/venv/lib/python3.7/site-packages/sympy/functions/elementary/piecewise.py", line 192, in eval
    c = c.as_set().as_relational(x)
  File "/home/dweindl/src/AMICI-devel/build/venv/lib/python3.7/site-packages/sympy/logic/boolalg.py", line 156, in as_set
    return self.subs(reps)._eval_as_set()
AttributeError: 'Xor' object has no attribute '_eval_as_set'

----------------------------------------------------------------------
Ran 1 test in 0.142s

FAILED (errors=1)
```

**Comment by paulstapor** [comment]
> FYI: For testing, on #789 you can now simply run `scripts/run-SBMLTestsuite.sh 201,279` to run only the affected cases.

Cool feature, but so far only in test_action branch, not yet in develop...
I'd be happy to branch a fixing_branch out of test_action in this case, instead of develop, but that's not the best style... Any idea? Copying the changes relevant for this from test_action as a first commit of a new fixing_branch, and hoping that those won't be changed again in test_action, hence praying for no merge_conflicts?

**Comment by dweindl** [comment]
> fixing_branch out of test_action in this case, instead of develop, but that's not the best style

I don't see a problem there

**Comment by paulstapor** [comment]
Okay

**Comment by paulstapor** [comment]
That's somewhat painful...
Sympy does have Xor, and it passes it as `Xor(*args)`, but the error here claims that this is an incorrect way of calling it...
I hope I can fix that today...

**Comment by dweindl** [comment]
Would be great if you could fix it. As as short-term workaround, we can go for a `SBMLException` with `Xor`, so then at least the testsuite does not fail. But since @FFroehlich mentioned it used to work, it should be fixable.

**Comment by paulstapor** [comment]
Okay, I've been looking a little into sympy. It seems like this is actually an error within Sympy. Boolean operations use to have a subroutine `_eval_as_set`, which is there for the routines `Or, And, Not ...`, but there's simply code missing in the function `Xor`

**Comment by paulstapor** [comment]
Suggestions? I would say we could/should/want to write this somehow to the Sympy developers...
Besides that, raising an "Xor"-Error might be a good option...
Or just reparsing the logic in it into "ands" and "ors" ...

**Comment by FFroehlich** [comment]
> Okay, I've been looking a little into sympy. It seems like this is actually an error within Sympy. Boolean operations use to have a subroutine `_eval_as_set`, which is there for the routines `Or, And, Not ...`, but there's simply code missing in the function `Xor`

```
>>> Xor(sp.Symbol('a'), sp.Symbol('b'))
Xor(a, b)
>>> Xor(True, False)
True
```
 cannot reproduce your issue

**Comment by dweindl** [comment]
> cannot reproduce your issue
```
import sympy as sp
sp.Piecewise((sp.Symbol("p1"), sp.sympify("Xor(S2 > 4, S2 < 1, S2 < 2)")), (sp.Symbol("p2"), True))
```

**Comment by dweindl** [comment]
@paulstapor Can report this at sympy and go for a `SBMLException` until you get feedback?

**Comment by FFroehlich** [comment]
Ah I see, so the problem is not `Xor` itself but using `Xor` in a piecewise function.

**Comment by paulstapor** [comment]
The problem is not Xor by itself.
The Problem is that the function `sympy.Piecewise` is calling a subroutine of a boolean operation, which is called `_eval_as_set()`. Most boolean operations seem to have this subroutine and it hence causes no issues. However, `Xor()` is lacking it...
Actually, the problem could either be in `Piecewise` or in `Xor`. However, `_eval_as_set()` is something which one can make sense of for logical operations. And as other booleans have it, I rather guess it's an error in `Xor`...
I will report it to sympy and will implement an Exception for that.

**Comment by paulstapor** [comment]
Okay. That should be done in #794 , but this one was branched out from `test_action`. So, it might be that some stuff is not as you would expect it... please review everything which is not sbml_import.py carefully with respect to that...
