### ISSUE TITLE
Use custom swig functions instead of setuptools for generated model extension (was: swig problem when create model)

### ISSUE THREAD

**Issue by DantongWang** [ICB-DCM/AMICI#978]
Hello, I wanted to compile my model and I did `model = importer.create_model()`, then I got errors like this:
```
error: command 'swig' failed with exit status 1

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dantongwang/dantong_windows/python_toolbox/pyPESTO/pypesto/objective/petab_import.py", line 137, in create_model
    self.compile_model(*args, **kwargs)
  File "/home/dantongwang/dantong_windows/python_toolbox/pyPESTO/pypesto/objective/petab_import.py", line 200, in compile_model
    **kwargs)
  File "/home/dantongwang/.local/lib/python3.6/site-packages/amici/logging.py", line 144, in wrapper_timer
    rval = func(*args, **kwargs)
  File "/home/dantongwang/.local/lib/python3.6/site-packages/amici/petab_import.py", line 468, in import_model
    **kwargs)
  File "/home/dantongwang/.local/lib/python3.6/site-packages/amici/sbml_import.py", line 274, in sbml2amici
    exporter.compileModel()
  File "/home/dantongwang/.local/lib/python3.6/site-packages/amici/logging.py", line 144, in wrapper_timer
    rval = func(*args, **kwargs)
  File "/home/dantongwang/.local/lib/python3.6/site-packages/amici/ode_export.py", line 1925, in compileModel
    verbose=self.verbose <= logging.DEBUG)
  File "/home/dantongwang/.local/lib/python3.6/site-packages/amici/ode_export.py", line 2010, in _compileCCode
    check=True)
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/dantongwang/dantong_windows/projects/AML_cDNA/python/amici_models/simple/setup.py', '--verbose', 'build_ext', '--build-lib=/home/dantongwang/dantong_windows/projects/AML_cDNA/python/amici_models/simple']' returned non-zero exit status 1.
```

**Comment by DantongWang** [comment]
Now it works for me... I installed `swig` instead of `swig3.0`.

**Comment by dweindl** [comment]
As amici installation succeeded, I assume swig is installed somewhere.

Maybe due to swig only being available as `swig3.0` on current Ubuntu.
Should be globally fixable with `sudo ln -s /usr/bin/swig3.0 /usr/bin/swig`, or as regular user, by putting a respective symlink in some directory on PATH.

Should still be fixed in AMICI. For amici base installation, we use a custom swig wrapper which finds that swig. For the model packages we rely on setuptools which does not handle that well.

**Comment by dweindl** [comment]
Reopening, since it will annoy other users as well.
